title = "Def Intelligence"
baseURL = "https://defintelligence.fr/"
defaultContentLanguage = "fr"
enableRobotsTXT = true
summaryLength = 30

[build]
  writeStats = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.120.0"
  [[module.imports]]
    path = "github.com/gethinode/hinode"

[outputs]
  home = ["HTML", "RSS", "JSON", "SITEMAP"]

[taxonomies]
  tag = "tags"
  category = "categories"
