title = "Defence Intelligence"
baseURL = "https://defintelligence.fr/"
defaultContentLanguage = "fr"
enableRobotsTXT = true
summaryLength = 30

[build]
  writeStats = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.146.0"
  [[module.imports]]
    path = "github.com/gethinode/hinode/v3"
  [[module.imports]]
    path = "github.com/gethinode/mod-blocks/v2"

ignoreLogs = ['warn-invalid-arguments']

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
